/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TigerBasicNFT } from "./TigerBasicNFT";

export { TigerBasicNFT__factory } from "./factories/TigerBasicNFT__factory";
